spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/book_social_network
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: localhost
        port: 1025
        username: username
        password: password
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls: 
                    enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000

application:
    security:
        jwt:
            secret-key: 8zp47h2o#xo0v_2b0&ryvnzeij5^=9+pys#ohmwlr7yp7%rek3
            expiration: 8640000
    mailing:
        frontend:
            activation_url: http://localhost:4200/activate-account
server:
    port: 8088